### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by marcelloh** [waxdred/GoHotReload#14]
Installed it with
go install github.com/waxdred/GoHotReload@latest

I can start it with :
GoHotReload
(not gohot)

Then it seeks the config.yml inside of:
~/go/bin/config/config.yml: no such file or directory

while I expect it to find the config file inside of the project that I run this tool from.

(BTW config.yml is a bad name, beter name it gohotreload_config.yml or something that will "couple" the config to the tool)

**Comment by waxdred** [comment]
I wouldn't recommend doing an installation via 'go install github.com/waxdred/GoHotReload@latest' because it requires the configuration file and not just the binary. I suggest you clone the project using Git, create your configuration in './config/config.yaml', and then build the project with 'make build'. Afterward, you'll be able to use the binary.
